name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check project files
        run: |
          ls -la
          ls -la src

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t mahjabeensiddiqui/task-manager:latest .

      - name: Push Docker image
        run: |
          docker push mahjabeensiddiqui/task-manager:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull mahjabeensiddiqui/task-manager:latest
            docker stop task-manager || true
            docker rm task-manager || true
            docker run -d \
              --name task-manager \
              --restart unless-stopped \
              -p 80:80 \
              mahjabeensiddiqui/task-manager:latest
            docker image prune -f