name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check project files
        run: |
          ls -la
          ls -la src

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image
        run: |
          docker build -t mahjabeensiddiqui/task-manager:latest .

      - name: Push Docker image
        run: |
          docker push mahjabeensiddiqui/task-manager:latest

      - name: CICD success
        run: |
          echo "Docker image successfully pushed to Docker Hub"